################################################################################
# 自动生成的文件。不要编辑！
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
applications/macAPP/Src \
applications/macBSP/Src \
applications/macGUI/lvgl_demos \
applications/macGUI/lvgl_fonts \
applications/macGUI/lvgl_gui \
applications/macGUI/porting \
applications/macSYS/Src \
applications/macTask \
applications \
cubemx/Src \
drivers \
libraries/CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc \
libraries/CMSIS/Device/ST/STM32F1xx/Source/Templates \
libraries/STM32F1xx_HAL_Driver/Src/Legacy \
libraries/STM32F1xx_HAL_Driver/Src \
packages/LVGL-v8.3.10/env_support/rt-thread \
packages/LVGL-v8.3.10/src/core \
packages/LVGL-v8.3.10/src/draw/arm2d \
packages/LVGL-v8.3.10/src/draw \
packages/LVGL-v8.3.10/src/draw/nxp/pxp \
packages/LVGL-v8.3.10/src/draw/nxp/vglite \
packages/LVGL-v8.3.10/src/draw/renesas \
packages/LVGL-v8.3.10/src/draw/sdl \
packages/LVGL-v8.3.10/src/draw/stm32_dma2d \
packages/LVGL-v8.3.10/src/draw/sw \
packages/LVGL-v8.3.10/src/draw/swm341_dma2d \
packages/LVGL-v8.3.10/src/extra/layouts/flex \
packages/LVGL-v8.3.10/src/extra/layouts/grid \
packages/LVGL-v8.3.10/src/extra/libs/bmp \
packages/LVGL-v8.3.10/src/extra/libs/ffmpeg \
packages/LVGL-v8.3.10/src/extra/libs/freetype \
packages/LVGL-v8.3.10/src/extra/libs/fsdrv \
packages/LVGL-v8.3.10/src/extra/libs/gif \
packages/LVGL-v8.3.10/src/extra/libs/png \
packages/LVGL-v8.3.10/src/extra/libs/qrcode \
packages/LVGL-v8.3.10/src/extra/libs/rlottie \
packages/LVGL-v8.3.10/src/extra/libs/sjpg \
packages/LVGL-v8.3.10/src/extra \
packages/LVGL-v8.3.10/src/extra/others/fragment \
packages/LVGL-v8.3.10/src/extra/others/gridnav \
packages/LVGL-v8.3.10/src/extra/others/ime \
packages/LVGL-v8.3.10/src/extra/others/imgfont \
packages/LVGL-v8.3.10/src/extra/others/monkey \
packages/LVGL-v8.3.10/src/extra/others/msg \
packages/LVGL-v8.3.10/src/extra/others/snapshot \
packages/LVGL-v8.3.10/src/extra/themes/basic \
packages/LVGL-v8.3.10/src/extra/themes/default \
packages/LVGL-v8.3.10/src/extra/themes/mono \
packages/LVGL-v8.3.10/src/extra/widgets/animimg \
packages/LVGL-v8.3.10/src/extra/widgets/calendar \
packages/LVGL-v8.3.10/src/extra/widgets/chart \
packages/LVGL-v8.3.10/src/extra/widgets/colorwheel \
packages/LVGL-v8.3.10/src/extra/widgets/imgbtn \
packages/LVGL-v8.3.10/src/extra/widgets/keyboard \
packages/LVGL-v8.3.10/src/extra/widgets/led \
packages/LVGL-v8.3.10/src/extra/widgets/list \
packages/LVGL-v8.3.10/src/extra/widgets/menu \
packages/LVGL-v8.3.10/src/extra/widgets/meter \
packages/LVGL-v8.3.10/src/extra/widgets/msgbox \
packages/LVGL-v8.3.10/src/extra/widgets/span \
packages/LVGL-v8.3.10/src/extra/widgets/spinbox \
packages/LVGL-v8.3.10/src/extra/widgets/spinner \
packages/LVGL-v8.3.10/src/extra/widgets/tabview \
packages/LVGL-v8.3.10/src/extra/widgets/tileview \
packages/LVGL-v8.3.10/src/extra/widgets/win \
packages/LVGL-v8.3.10/src/font \
packages/LVGL-v8.3.10/src/hal \
packages/LVGL-v8.3.10/src/misc \
packages/LVGL-v8.3.10/src/widgets \
rt-thread/components/drivers/hwtimer \
rt-thread/components/drivers/i2c \
rt-thread/components/drivers/ipc \
rt-thread/components/drivers/misc \
rt-thread/components/drivers/rtc \
rt-thread/components/drivers/serial \
rt-thread/components/drivers/spi \
rt-thread/components/finsh \
rt-thread/components/libc/compilers/common \
rt-thread/components/libc/compilers/newlib \
rt-thread/components/utilities/ulog/backend \
rt-thread/components/utilities/ulog \
rt-thread/libcpu/arm/common \
rt-thread/libcpu/arm/cortex-m3 \
rt-thread/src \

